import AnimatedText from "@/Components/AnimatedText";
import { GithubIcon } from "@/Components/Icons";
import Layout from "@/Components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import dishcoveryImg from "../../public/images/projects/Dishcovery.png";
import trimrrImg from "../../public/images/projects/Trimrr.png";
import fusionDexImg from "../../public/images/projects/FusionDex.png";
import quickBuyImg from "../../public/images/projects/QuickBuy.png";
import Transitions from "@/Components/Transitions";

const FeatureProject = ({ type, title, summary, img, github, link }) => {
  return (
    <article className="dark:bg-dark dark:border-light w-full flex relative items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12 rounded-br-2xl lg:flex-col lg:p-8 xs:rounded-2xl xs:rounded-br-3xl xs:p-4">
      <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] bg-dark rounded-br-3xl dark:bg-primary xs:-right-3 sm:h-[102%] xs:w-[100%] xs:rounded-[1.5rem]" />

      <Link
        href={link}
        target="_blank"
        className=" w-1/2 cursor-pointer overflow-hidden rounded-lg lg:w-full"
      >
        <Image
          src={img}
          alt={title}
          className="w-full h-auto"
          priority
          sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
        />
      </Link>

      <div className="w-1/2 flex flex-col items-start justify-between pl-6 lg:w-full lg:pl-0 lg:pt-6 ">
        <span className="text-primary dark:text-primaryDark font-medium text-xl xs:text-base">
          {type}
        </span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset-2 dark:hover:un"
        >
          <h2 className="my-2 w-full text-left text-4xl font-bold dark:text-light sm:text-sm">
            {title}
          </h2>
        </Link>
        <p className="my-2 font-medium text-dark dark:text-light">{summary}</p>
        <div className="mt-2 flex items-center">
          <Link href={github} target="_blank" className="w-10">
            {" "}
            <GithubIcon />
          </Link>
          <Link
            href={link}
            target="_blank"
            className="ml-4 rounded-lg bg-dark dark:bg-light dark:text-dark text-light p-2 px-6 text-lg font-semibold sm:px-4 sm:text-base "
          >
            {" "}
            Visit Project
          </Link>
        </div>
      </div>
    </article>
  );
};

const Project = ({ type, title, summary, img, github, link }) => {
  return (
    <>
      <article className=" dark:bg-dark dark:border-light w-full flex relative shadow-2xl items-center flex-col justify-center rounded-2xl border border-solid border-dark bg-light p-6 xs:p-4">
        <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-primaryDark md:-right-2 md:w-[101%] sm:h-[102%] xs:rounded-[1.5rem]" />

        <Link
          href={link}
          target="_blank"
          className=" w-full cursor-pointer overflow-hidden rounded-lg"
        >
          <Image src={img} alt={title} className="w-full h-auto" />
        </Link>

        <div className="w-full flex flex-col items-start justify-between mt-4">
          <span className="text-primary dark:text-primaryDark font-medium text-xl lg:text-lg md:text-base ">
            {type}
          </span>
          <Link
            href={link}
            target="_blank"
            className="hover:underline underline-offset-2"
          >
            <h2 className="my-2 w-full dark:text-light text-left text-3xl font-bold lg:text-xl">
              {title}
            </h2>
          </Link>
          <p className="my-2 font-medium text-dark dark:text-light sm:text-sm">
            {summary}
          </p>
          <div className="w-full justify-between mt-2 flex items-center">
            <Link href={github} target="_blank" className="w-10 md:w-6">
              {" "}
              <GithubIcon className={"dark:fill-light"} />
            </Link>
            <Link
              href={link}
              target="_blank"
              className="ml-4 rounded-lg bg-dark text-light dark:bg-light dark:text-dark p-2 px-6 text-lg font-semibold md:text-base"
            >
              {" "}
              Visit
            </Link>
          </div>
        </div>
      </article>
    </>
  );
};

const projects = () => {
  return (
    <>
      <Head>
        <title>Rahul | Project Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitions />
      <main className="w-full mb-16 flex flex-col justify-center items-center dark:text-light">
        <Layout className="pt-16">
          <AnimatedText
            text="Innovation Beats Convention!"
            className="mb-16 lg:!text-7xl sm:!mb-8 sm:!text-6xl xs:!text-4xl"
          />
          <div className="grid grid-cols-12 gap-24 xl:gap-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-5 ">
            <div className="col-span-12">
              <FeatureProject
                type={"FEATURE PROJECT"}
                title={"QuickBuy"}
                link="https://quick-buy-frontend.vercel.app/"
                github={"https://github.com/rajanarahul93/QuickBuy"}
                img={quickBuyImg}
                summary="QuickBuy is a full-stack e-commerce application built with the MERN stack. It supports product browsing, cart management, order placement, admin product uploads, and secure payments using Stripe. Features include JWT authentication, Cloudinary image uploads, and a powerful admin dashboard for managing products and orders."
              />
            </div>

            <div className="col-span-12">
              <FeatureProject
                type={"FEATURE PROJECT"}
                title={"Trimrr"}
                link="https://trimrr-amber.vercel.app/"
                github={"https://github.com/rajanarahul93/trimrr"}
                img={trimrrImg}
                summary="Trimrr is a full-stack modern URL shortener with real-time click analytics. Built with React (Vite), Supabase, and Tailwind CSS, it supports custom links, QR code generation, device/location tracking, and a secure dashboard with visualized stats via Recharts."
              />
            </div>

            <div className="col-span-6 sm:col-span-12">
              <Project
                type={"PROJECT"}
                title={"FusionDex"}
                link="https://fusion-dex-alpha.vercel.app/"
                github={"https://github.com/rajanarahul93/FusionDex"}
                img={fusionDexImg} // Make sure to import this image correctly
                summary="FusionDex is an interactive Pokémon fusion and battle simulation app built with React, Tailwind CSS, Framer Motion, and PokéAPI. Users can explore, fuse Pokémon, simulate battles, and visualize stats with a responsive and animated UI."
              />
            </div>

            <div className="col-span-6 sm:col-span-12">
              <Project
                type={"PROJECT"}
                title={"DishCovery"}
                link="https://dishcovery-rouge.vercel.app/"
                github={"https://github.com/rajanarahul93/Dishcovery"}
                img={dishcoveryImg}
                summary="• Dishcovery is a web app that lets users search for recipes by name or ID using The Meal Database API. It displays detailed recipe information, including ingredients, instructions, and video tutorials. Built with React, it features smooth navigation via React Router and video playback with React Player."
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default projects;
